// Wrapper config generation: lets the vci CLI run
//   VCI_OUT=<dir> vitest run --config <wrapper> <files…>
// without the user editing their own config. The wrapper imports the user's config (Vite's
// config loader bundles it, so TypeScript configs and `import.meta.url` keep working) and
// appends the @vci/vitest plugin.

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const INDEX_URL = pathToFileURL(fileURLToPath(new URL("./index.js", import.meta.url))).href;

const CONFIG_NAMES = [
  "vitest.config.ts",
  "vitest.config.mts",
  "vitest.config.cts",
  "vitest.config.js",
  "vitest.config.mjs",
  "vitest.config.cjs",
  "vite.config.ts",
  "vite.config.mts",
  "vite.config.cts",
  "vite.config.js",
  "vite.config.mjs",
  "vite.config.cjs",
];

/**
 * Find the config file Vitest would pick in `root` (vitest.config.* before vite.config.*).
 * @param {string} root
 * @returns {string | null}
 */
export function findUserConfig(root) {
  for (const n of CONFIG_NAMES) {
    const p = path.join(root, n);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

/**
 * @typedef {object} WrapperOptions
 * @property {string} [root] project directory (default: cwd)
 * @property {string | false | null} [configFile] user config path; undefined = auto-detect; false/null = none
 * @property {string} [outFile] where to write the wrapper (default: `<root>/node_modules/.vci/vitest.config.vci.mjs`
 *   when `<root>/node_modules` exists, else a fresh temp dir)
 * @property {string} [outDir] bake an output dir into the plugin options (default: rely on VCI_OUT at run time)
 */

/**
 * Write a Vitest config that merges the user's config with the @vci/vitest plugin.
 * @param {WrapperOptions} [opts]
 * @returns {string} absolute path of the wrapper config
 */
export function writeWrapperConfig(opts = {}) {
  const root = path.resolve(opts.root || process.cwd());
  const configFile =
    opts.configFile === false || opts.configFile === null
      ? null
      : opts.configFile
        ? path.resolve(root, opts.configFile)
        : findUserConfig(root);
  let outFile = opts.outFile ? path.resolve(opts.outFile) : null;
  if (!outFile) {
    const nm = path.join(root, "node_modules");
    const dir = fs.existsSync(nm)
      ? path.join(nm, ".vci")
      : fs.mkdtempSync(path.join(os.tmpdir(), "vci-wrapper-"));
    outFile = path.join(dir, "vitest.config.vci.mjs");
  }
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  const pluginOptions = opts.outDir ? { outDir: path.resolve(opts.outDir) } : {};

  const lines = [
    "// Generated by @vci/vitest writeWrapperConfig(). Do not edit.",
    configFile ? `import * as userModule from ${JSON.stringify(configFile)};` : "const userModule = {};",
    "",
    `const pluginUrl = ${JSON.stringify(INDEX_URL)};`,
    `const pluginOptions = ${JSON.stringify(pluginOptions)};`,
    `const projectRoot = ${JSON.stringify(root)};`,
    "",
    "export default async function vciWrappedConfig(env) {",
    "  // Loaded natively (not bundled with the config) so the plugin's file paths stay valid.",
    "  const { default: vci } = await import(/* @vite-ignore */ pluginUrl);",
    "  let config = userModule.default ?? {};",
    "  if (typeof config === 'function') config = await config(env);",
    "  config = await config;",
    "  config = { ...(config ?? {}) };",
    "  config.plugins = [...(config.plugins ?? []), vci(pluginOptions)];",
    "  if (config.root === undefined) config.root = projectRoot;",
    "  return config;",
    "}",
    "",
  ];
  fs.writeFileSync(outFile, lines.join("\n"));
  return outFile;
}
