//! Crate c: a file outside its package through include_str!, and a constant
//! generated by build.rs from a file it declares with rerun-if-changed.

include!(concat!(env!("OUT_DIR"), "/generated.rs"));

pub const BANNER: &str = include_str!("../../shared/c.txt");

#[cfg(test)]
mod tests {
    #[test]
    fn banner_and_mode() {
        assert_eq!(super::BANNER.trim(), "welcome");
        assert_eq!(super::MODE, "fast");
    }
}
